FROM openjdk:17.0.1-jdk-slim

EXPOSE 8080

COPY build/libs/*.jar app.jar

ARG DB_URL
ENV DB_URL ${DB_URL}
ARG DB_DRIVER
ENV DB_DRIVER ${DB_DRIVER}
ARG DB_USERNAME
ENV DB_USERNAME ${DB_USERNAME}
ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD}

ENTRYPOINT ["java", "-jar", "-Duser.timezone=Asia/Seoul", "/app.jar"]